theme = "slick"
icons = "awesome5"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "nvidia_gpu"
label = "GTX980"
show_memory = true
show_clocks = true
show_power_draw = true
interval = 1

[[block]]
block = "net"
device = "enp4s0"
format = "{speed_down;K*b} {speed_up;K*b} {graph_down}"
interval = 1

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "temperature"
collapsed = false
interval = 1
format = "{min} min, {max} max, {average} avg"
chip = "k10temp-pci-00c3"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
